apiVersion: v1
kind: Pod

metadata:
  labels:
    name: mysql-web
    webserver: apache
  name: mysql-db1

spec:
  restartPolicy: Always
  containers:
    - image: mysql:5.7
      name: mysql-db1
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: hghfds634jhd
        - name: MYSQL_USER
          value: wpuser
        - name: MYSQL_PASSWORD
          value: DEVOPS12345
        - name: MYSQL_DATABASE
          value: wpdb
