apiVersion: v1
kind: Pod

metadata:
  labels:
    name: wordpress-web
    webserver: apache
  name: wordpress-web1

spec:
  restartPolicy: Always
  containers:
    - image: wordpress
      name: wordpress-web1
      env:
        - name: WORDPRESS_DB_HOST
          value: 192.168.87.129
        - name: WORDPRESS_DB_USER
          value: wpuser
        - name: WORDPRESS_DB_PASSWORD
          value: DEVOPS12345
        - name: WORDPRESS_DB_NAME
          value: wpdb
